### ISSUE TITLE
[Bug] MegaMacro UI won't populate in Dragonflight

### ISSUE THREAD

**Issue by Soromeister** [Sellorio/mega-macro#158] opened 2022-10-11 16:18 UTC
Hi @Sellorio, are there any plans to continue development of this addon in Dragonflight? Asking to know whether it's feasible to port all my macros to your addon, while Dragonflight approaches quickly with the pre-patch.

**Comment by sellorio2** [comment] 2022-10-11 22:49
Hopefully dragonflight either doesn't modify any macro system code or has its own new macro ui. I suspect the former in which case ignoring out of date addons should work.

I don't have any plans to play dragonflight at this time.

If you or someone else can confirm that the addon works in dragonflight I'll bump the version so you don't have to tick that box just for me :P

**Comment by jschick04** [comment] 2022-10-14 14:42
I have tested it in DF and PTR and the addon itself seems to work but the issue is the MegaMacro UI doesn't get populated, and the old macro window still gets displayed.
And when I say it works, any existing macro still works but unable to edit the actual macro or create any new macros since the default UI only shows the MegaMacro code.
![image](https://user-images.githubusercontent.com/17906967/195874325-8e860137-222f-4609-b66c-f37e98329347.png)

**Comment by sellorio2** [comment] 2022-10-15 00:17
Looks like the new tabs ui is a breaking change. Wouldn't be surprised if it's not too hard to fix. Maybe i'll make a level 1 character to test fixes without buying dragonflight or subbing.

**Comment by Soromeister** [comment] 2022-10-20 09:01
I can confirm the same behavior as @jschick04 found.. Was just a bit late to test this. I will update the issue title to make it a bug instead.

**Comment by durandal42** [comment] 2022-10-26 02:50
First day of 10.0, and I see similar UI as jschick04's screenshot, but the old macro UI is not also visible.

More concerningly, all of my existing megamacros (on my actionbars) do nothing when clicked.

**Comment by aurelion314** [comment] 2022-10-26 03:28
> More concerningly, all of my existing megamacros (on my actionbars) do nothing when clicked.

Same here. Its not just the UI, the macro's themselves do not currently work. 

I hope this can be fixed, because I rely heavily on mega macro and would hate to lose it.

**Comment by durandal42** [comment] 2022-10-26 04:34
One specific macro works!

```
		{
			["Scope"] = "gg",
			["Code"] = "#showtooltip\n/cast [button:1] Eternal Traveler's Hearthstone\n/stopmacro [button:1]\n/cast Revive Battle Pets\n/camp\n",
			["Id"] = 5,
			["StaticTexture"] = 134400,
			["ScopedIndex"] = 5,
			["DisplayName"] = "home",
		}, -- [13]
```

... sort of.

It does nothing if I left click it (intended to cast hearthstone and then /stopmacro), but it *does* log me out if I right-click it.

AFAICT none of my other macros work at all.

**Comment by aurelion314** [comment] 2022-10-26 05:14
I've found similar issues discussed with other addons. It sounds like blizzard messed up how clicks are registered for the "SecureActionButtonTemplate" frame, which is what the macros are. 

forum post: https://us.forums.blizzard.com/en/wow/t/dragonflight-click-bindings-broken/1361972/9
bug post: https://github.com/Stanzilla/WoWUIBugs/issues/283

**Comment by Sellorio** [comment] 2022-10-26 05:18
I'm done with wow for the foreseeable future and my only regret is not being able to continue maintaining this addon.

@aurelion314 if you'd be willing I'm happy to support you in updating the addon for 10.0. I am even happy to be in a call the whole time but I can't motivate myself to drive the development myself.

**Comment by aurelion314** [comment] 2022-10-26 05:23
@Sellorio Can't blame you heh. I don't mind helping maintain it, but first need to figure out if this event bug is even fixable. I'm trying some hacks right now but haven't got anything to work..

**Comment by durandal42** [comment] 2022-10-26 05:36
More anecdata: all(?) of my macros behave correctly *if I right-click them on my action bar*. Left-click doesn't work. Pressing an assigned keybind doesn't work.

**Comment by Dannez83** [comment] 2022-10-26 16:19
As mentioned there does seem to be a couple of different bugs. One to do with clicks/keybinds - which I think is a Blizzard issue, and one to do with the tabs ui. In addition to the above error, there are also the two below. 


```
90x Interface/SharedXML/SharedUIPanelTemplates.lua:503: attempt to index field 'Text' (a nil value)
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:503: in function `PanelTemplates_TabResize'
[string "*mega-macro.window.xml:316_OnLoad"]:1: in function <[string "*mega-macro.window.xml:316_OnLoad"]:1>

Locals:
tab = MegaMacro_FrameTab1 {
 0 = <userdata>
}
padding = -8
absoluteSize = nil
minWidth = nil
maxWidth = nil
absoluteTextSize = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Text' (a nil value)"
TAB_SIDES_PADDING = 20
```

```
15x Interface/SharedXML/SharedUIPanelTemplates.lua:619: attempt to index field 'Left' (a nil value)
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:619: in function `PanelTemplates_SelectTab'
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:484: in function `PanelTemplates_UpdateTabs'
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:465: in function `PanelTemplates_SetTab'
[string "@Interface/AddOns/MegaMacro/src/windows/mega-macro.window.lua"]:452: in function `MegaMacro_Window_OnLoad'
[string "*mega-macro.window.xml:39_OnLoad"]:2: in function <[string "*mega-macro.window.xml:39_OnLoad"]:1>

Locals:
tab = MegaMacro_FrameTab1 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Left' (a nil value)"
```

I haven't done any addon dev for years, but I will have a go at this tonight/tomorrow as I seriously cannot live without this addon

**Comment by Dannez83** [comment] 2022-10-26 16:49
Fix for keybinds/leftclick. Basically Left Click has to be explicitly declared now in he template macros that get written to the default macro storage 


E:\World of Warcraft\_retail_\Interface\AddOns\MegaMacro\src\engine
replace line 123
`"/click [btn:1] "..ClickyFrameName..macroId.." \n"..`

with 
`"/click [btn:1] "..ClickyFrameName..macroId.." LeftButton\n"..`

**Comment by durandal42** [comment] 2022-10-26 17:04
Confirmed that the keybind/leftclick solution from @Dannez83 works!

I still can't edit macros, but being able to use my existing ones is a huge step forward!

**Comment by Dannez83** [comment] 2022-10-26 17:08
> Confirmed that the keybind/leftclick solution from @Dannez83 works!
> 
> I still can't edit macros, but being able to use my existing ones is a huge step forward!

starting on that now

**Comment by Dannez83** [comment] 2022-10-26 17:28
Looks like they've changed some of the ui identifiers that are being inherited. Making progress
![Screenshot 2022-10-26 182803](https://user-images.githubusercontent.com/60705967/198095397-b846d113-1a6b-4ad7-b682-7040b8d716e9.png)

**Comment by aurelion314** [comment] 2022-10-26 17:52
@Dannez83 awesome find! I was worried we'd have to wait for Blizzard. 

Do you have a branch or fork that you're working on? I don't mind helping since I'm probably not alone in needing this to work before I can really enjoy anything in the new patch.

**Comment by Dannez83** [comment] 2022-10-26 18:05
> @Dannez83 awesome find! I was worried we'd have to wait for Blizzard.
> 
> Do you have a branch or fork that you're working on? I don't mind helping since I'm probably not alone in needing this to work before I can really enjoy anything in the new patch.

I hadn't set one up yet. Was going to do it if I fixed everything, but I'll happily set one up now and update with the changes I've made so far. Don't mind sharing the load

**Comment by Dannez83** [comment] 2022-10-26 19:56
@aurelion314 I've sent you an invite to the fork. I've got it to the point where all the tabs are appearing again. I believe what's stopping the macros showing up is related to the macro button that is used to add new macros.

fork is here for anyone else to download as well
https://github.com/Dannez83/mega-macro

**Comment by aurelion314** [comment] 2022-10-26 20:11
@Dannez83 Awesome thanks, I'm at the same spot I think. My current error is also a buttonName issue, which might be related to how the xml error (after the inheritance errors) had a problem on the getName() line.

I'll try out your fork and see if its different.

**Comment by aurelion314** [comment] 2022-10-26 20:42
So where I'm at: The code assumes each macro button in the edit window has an Icon and Name frame to go along with it. 

EX: _G['MegaMacro_MacroButton1'] 
It expects there to also be a  _G['MegaMacro_MacroButton1Name'] and _G['MegaMacro_MacroButton1Icon'], which are frames that it tries to modify. Problem is they don't exists and I don't see where they are supposed to be set. My guess is that the old inherited frame "SimplePopupButtonTemplate" which has been replaced with "SelectorButtonTemplate", used to generate that automatically.

@Sellorio Do you recall where/how the Icon and Name frames get created? Or am I right that its a template thing? For context, The error is when you open the macro menu, and it tries to fill the macro icons but while the button frame exists, it can't set the name/icon.

**Comment by aurelion314** [comment] 2022-10-26 21:02
@Dannez83 I have it functional! It works (I can modify and rebind macros, and see icons), but I commented out a few things so the macro names are hidden. Will have to fix it properly but this is progress! I might have to go soon so if I don't get around to pushing to your fork, here is what I did:

1. Change line 44 from 
`return _G[buttonName], _G[buttonName .. "Name"], _G[buttonName .. "Icon"]`
to
`return _G[buttonName], _G[buttonName .. "Name"], _G[buttonName].Icon`
(The Icon is a child of the button frame now, not its own global variable.)

2. Comment out any lines in the same file that use MegaMacro_FrameSelectedMacroButtonIcon
(this is the editing macro icon. temporary fix just hides it)

That, along with the other changes you've already done, was enough to make it functional.

**Comment by mgrune** [comment] 2022-10-26 21:15
Really appreciate you guys working so hard on the addon.  It's much appreciated.

**Comment by Dannez83** [comment] 2022-10-26 21:20
> @Dannez83 I have it functional! It works (I can modify and rebind macros, and see icons), but I commented out a few things so the macro names are hidden. Will have to fix it properly but this is progress! I might have to go soon so if I don't get around to pushing to your fork, here is what I did:
> 
> 1. Change line 44 from
>    `return _G[buttonName], _G[buttonName .. "Name"], _G[buttonName .. "Icon"]`
>    to
>    `return _G[buttonName], _G[buttonName .. "Name"], _G[buttonName].Icon`
>    (The Icon is a child of the button frame now, not its own global variable.)
> 2. Comment out any lines in the same file that use MegaMacro_FrameSelectedMacroButtonIcon
>    (this is the editing macro icon. temporary fix just hides it)
> 
> That, along with the other changes you've already done, was enough to make it functional.

Nice one @aurelion314. Well done. I'll update the fork

**Comment by Dannez83** [comment] 2022-10-26 21:43
@aurelion314 I think I've commented out everything needed but I'll leave it for you to update the fork just to be sure

**Comment by durandal42** [comment] 2022-10-26 21:58
> is there anything else you changed as that's not working for me

After downloading the latest code from https://github.com/Dannez83/mega-macro and applying the fix from @aurelion314 above, I get tabs ([Global][Paladin][Protection][Lintilla][Lintilla Protecti...]) but only two icons appear, and it's the same two (in the same positions) in each tab.

I can't meaningfully interact with this window yet.

**Comment by Dannez83** [comment] 2022-10-26 22:21
> > is there anything else you changed as that's not working for me
> 
> After downloading the latest code from https://github.com/Dannez83/mega-macro and applying the fix from @aurelion314 above, I get tabs ([Global][Paladin][Protection][Lintilla][Lintilla Protecti...]) but only two icons appear, and it's the same two (in the same positions) in each tab.
> 
> I can't meaningfully interact with this window yet.

I have updated with some additional lines commented out. Try downloading it again

**Comment by sellorio2** [comment] 2022-10-26 22:23
@Dannez83 @aurelion314 this is good stuff! Thanks for the updates. Don't forget to add credits to yourselves in the readme for updating the addon for Dragonflight when you're done. And once it's all done I'll accept the PR and upload it to curse (with credits there too).

**Comment by durandal42** [comment] 2022-10-26 22:28
> Try downloading it again.

I'm confused; the last commit I can see here https://github.com/Dannez83/mega-macro/commits/master was ~3 hours ago, well before my most recent download (and then patch with @aurelion314's tweaks).

**Comment by Dannez83** [comment] 2022-10-26 22:33
> > Try downloading it again.
> 
> I'm confused; the last commit I can see here https://github.com/Dannez83/mega-macro/commits/master was ~3 hours ago, well before my most recent download (and then patch with @aurelion314's tweaks).

sorry, in my rush to head off to bed I forgot to actually press the commit button. Done now

**Comment by durandal42** [comment] 2022-10-26 23:00
Good news and bad news:

Good: the latest commit has the [Global] tab working, and all the macros in there are editable and can be dragged onto action bars, where they then work.

Bad: every macro in the *other* tabs [Class][Specialization][CharacterName][CharacterName Specialization] are *gone*, and the macros from these tabs on my bars which functioned (but couldn't be edited) before this update are now dead.

**Comment by durandal42** [comment] 2022-10-26 23:08
~3 hours ago version didn't fix it.

I've reverted all the way back to latest CurseForge version, and re-applied the fix from https://github.com/Sellorio/mega-macro/issues/158#issuecomment-1292327472 

I also restored the copy of SavedVariables/MegaMacro.lua I made the night before 10.0, so I'm not sure whether the disappearance of my non-global macros was destructive.

**Comment by Fluke667** [comment] 2022-10-26 23:17
Not working

**Comment by aurelion314** [comment] 2022-10-27 01:24
> Bad: every macro in the _other_ tabs [Class][Specialization][CharacterName][CharacterName Specialization] are _gone_, and the macros from these tabs on my bars which functioned (but couldn't be edited) before this update are now dead.

I have pushed a fixed version that shouldn't do that anymore. It also fixes icons, names, and hides one error I haven't fixed yet.

Shift clicking on spells does not work yet. Still trying to figure that out, but sharing what I have so far since it is at least functional and gets everyone their macros back.

Get it here: https://github.com/Dannez83/mega-macro

**Comment by kingreboot** [comment] 2022-10-27 01:28
> @aurelion314 I've sent you an invite to the fork. I've got it to the point where all the tabs are appearing again. I believe what's stopping the macros showing up is related to the macro button that is used to add new macros.
> 
> fork is here for anyone else to download as well https://github.com/Dannez83/mega-macro

Thanks for putting in the work, there is no real way to start a conversation on your project and was hoping to ask about setting up a release for that project in a way I could download it via wowup

**Comment by aurelion314** [comment] 2022-10-27 01:31
> Thanks for putting in the work, there is no real way to start a conversation on your project and was hoping to ask about setting up a release for that project in a way I could download it via wowup

The author of the addon is still active in this thread, so once its fully fixed I'm sure he'll approve it here. Then you can update it as normal. For now we are using that fork to work on it.

**Comment by kingreboot** [comment] 2022-10-27 01:33
got it, thanks for the update

**Comment by jschick04** [comment] 2022-10-27 02:51
Looks like something changed and now this change has to be reverted

E:\World of Warcraft_retail_\Interface\AddOns\MegaMacro\src\engine\mega-macro-engine.lua
replace line 123
"/click [btn:1] "..ClickyFrameName..macroId.." \n"..

with
"/click [btn:1] "..ClickyFrameName..macroId.." LeftButton\n"..

**Comment by tomleung0117** [comment] 2022-10-27 05:14
My macros are back, but couldn't be used by hotkey/left click etc... thoughts? 

thanks a lot tho guys.

**Comment by aurelion314** [comment] 2022-10-27 05:29
@jschick04 @tomleung0117

I just let my client update and it still works. Version 10.0.0.46313. It did multiple updates at once, so maybe they broke it only temporarily? Anyway if it still doesn't work, can you verify and share your client version?

**Comment by tomleung0117** [comment] 2022-10-27 06:00
@aurelion314 

the verison i have is 8fdd7e , which was uploaded 5hours ago. Is this the correct one ? not very familiar with git hub btw.. ty!

**Comment by aurelion314** [comment] 2022-10-27 06:09
> the verison i have is 8fdd7e (https://github.com/Dannez83/mega-macro) , which was uploaded 5hours ago. Is this the correct one ? not very familiar with git hub btw.. ty!

Yes that one is currently working for me.

**Comment by wing5wong** [comment] 2022-10-27 06:17
just chiming in - macro icons etc load, can be editted and so on, but do not work with keybinds or click.
actionbar flashes as if bind is going through ,but no spells are cast

**Comment by tomleung0117** [comment] 2022-10-27 06:31
> 

yup it works for me too!

**Comment by gijsprins93** [comment] 2022-10-27 06:36
How do i use the Fork one? Do i have to manually change the lua files myself or can i copy/replace some files?

**Comment by aurelion314** [comment] 2022-10-27 06:43
> How do i use the Fork one? Do i have to manually change the lua files myself or can i copy/replace some files?

@gijsprins93 You have to replace the files with the forked files. Easiest to just replace everything. 
Files are in `World of Warcraft\_retail_\Interface\AddOns\MegaMacro`

You may have to tweak one line as mentioned by [wing5wong](https://github.com/wing5wong). Personally changing that line breaks it for me, so try the forked version first and see.

**Comment by gijsprins93** [comment] 2022-10-27 07:12
> > How do i use the Fork one? Do i have to manually change the lua files myself or can i copy/replace some files?
> 
> @gijsprins93 You have to replace the files with the forked files. Easiest to just replace everything. Files are in `World of Warcraft\_retail_\Interface\AddOns\MegaMacro`
> 
> You may have to tweak one line as mentioned by [wing5wong](https://github.com/wing5wong). Personally changing that line breaks it for me, so try the forked version first and see.

But it won't let me download it anywhere tho.

**Comment by gijsprins93** [comment] 2022-10-27 07:57
i'm an idiot. never mind my question

**Comment by Lowlander0031** [comment] 2022-10-27 08:33
Hello and ty for the updates. Quick question all the macro's are displayed as ? atm and not with their icons?!?

**Comment by Dannez83** [comment] 2022-10-27 08:42
> Hello and ty for the updates. Quick question all the macro's are displayed as ? atm and not with their icons?!? Before I updated it with the patches the macro's were showing with their icons just fine.
> 
> notice now the macro's actually don't work anymore after the patching and reinstalled the addon so I can at least use the macro's. Must have done something wrong patching.

Best just to hang on for a bit. We're still working through a couple of bugs. Once done @Sellorio will push out the fix to addon sites

**Comment by Soromeister** [comment] 2022-10-27 13:11
Just came back to see activity here. I'd like to thank everyone involved so far. I simply hope Blizzard will one day increase the limit of their macros and polish their whole macro system.

I did find an alternative to this in the [Dominos Action Bars] addon, as it has a feature called Paging, which can also be configured based on conditionals such as [harm]:

![image](https://user-images.githubusercontent.com/45243695/198147021-bb37b2db-659e-4eca-9439-1fdba3be236a.png)
![image](https://user-images.githubusercontent.com/45243695/198147443-6ccf6154-470b-493a-abb2-b0ea0d0eff80.png)
![image](https://user-images.githubusercontent.com/45243695/198147491-d64350f3-ee7a-4086-a079-292a818e057c.png)
![image](https://user-images.githubusercontent.com/45243695/198147529-4ca28b35-1f4c-4e93-8cd6-f5467227ef35.png)

Thus, a combination between some simple macros and this Paging feature can actually replace the need to write macros longer than 255 characters.

**Comment by kasiopec** [comment] 2022-10-27 16:25
> Just came back to see activity here. I'd like to thank everyone involved so far. I simply hope Blizzard will one day increase the limit of their macros and polish their whole macro system.
> 
> I did find an alternative to this in the [Dominos Action Bars] addon, as it has a feature called Paging, which can also be configured based on conditionals such as [harm]:
> 
> ![image](https://user-images.githubusercontent.com/45243695/198147021-bb37b2db-659e-4eca-9439-1fdba3be236a.png) ![image](https://user-images.githubusercontent.com/45243695/198147443-6ccf6154-470b-493a-abb2-b0ea0d0eff80.png) ![image](https://user-images.githubusercontent.com/45243695/198147491-d64350f3-ee7a-4086-a079-292a818e057c.png) ![image](https://user-images.githubusercontent.com/45243695/198147529-4ca28b35-1f4c-4e93-8cd6-f5467227ef35.png)
> 
> Thus, a combination between some simple macros and this Paging feature can actually replace the need to write macros longer than 255 characters.

Dominos is no longer maintained addon, same goes with raven.

**Comment by georgi-chinov** [comment] 2022-10-27 17:11
I don't see the connection between bar paging and macros, sorry :D

**Comment by BoulderSean** [comment] 2022-10-27 19:56
> I don't see the connection between bar paging and macros, sorry :D

bartender4 has paging as well. it's what i ended up using for now to get things working. basically, as a druid anyway, i break my macros up into 3 or 4 separate macros and page to a new bar for humanoid/bear/cat. 

that was my solution until either this or M6 is fixed.

**Comment by BoulderSean** [comment] 2022-10-27 19:57
> > Just came back to see activity here. I'd like to thank everyone involved so far. I simply hope Blizzard will one day increase the limit of their macros and polish their whole macro system.
> > I did find an alternative to this in the [Dominos Action Bars] addon, as it has a feature called Paging, which can also be configured based on conditionals such as [harm]:
> 
> > Thus, a combination between some simple macros and this Paging feature can actually replace the need to write macros longer than 255 characters.
> 
> Dominos is no longer maintained addon, same goes with raven.

there is a community fix for raven. working good for me. check the comments on it's curseforge page

**Comment by EryChu** [comment] 2022-10-28 03:13
> My macros are back, but couldn't be used by hotkey/left click etc... thoughts?
> 
> thanks a lot tho guys.

Mine is doing the same thing.  I can make new ones but when I add them to my action bar I cannot interact with it.
Thank you for your time on this!  I really appreciate it.

**Comment by jschick04** [comment] 2022-10-28 04:20
> > My macros are back, but couldn't be used by hotkey/left click etc... thoughts?
> > thanks a lot tho guys.
> 
> Mine is doing the same thing. I can make new ones but when I add them to my action bar I cannot interact with it. Thank you for your time on this! I really appreciate it.

This line needs to be reverted back to the following

E:\World of Warcraft_retail_\Interface\AddOns\MegaMacro\src\engine\mega-macro-engine.lua
replace line 123
"/click [btn:1] "..ClickyFrameName..macroId.." \n"..

**Comment by aurelion314** [comment] 2022-10-28 04:27
> This line needs to be reverted back to the following
> 
> E:\World of Warcraft_retail_\Interface\AddOns\MegaMacro\src\engine\mega-macro-engine.lua replace line 123 "/click [btn:1] "..ClickyFrameName..macroId.." \n"..

My new fork fixes that and a bunch of other stuff: https://github.com/aurelion314/mega-macro

**Comment by EryChu** [comment] 2022-10-28 06:12
> > This line needs to be reverted back to the following
> > E:\World of Warcraft_retail_\Interface\AddOns\MegaMacro\src\engine\mega-macro-engine.lua replace line 123 "/click [btn:1] "..ClickyFrameName..macroId.." \n"..
> 
> My new fork fixes that and a bunch of other stuff: https://github.com/aurelion314/mega-macro

This works perfectly for me!  Thank you very much!

**Comment by PunkROC01** [comment] 2022-10-28 06:35
@aurelion314 Do we need to download everything listed there, or just the SRC folder and MegaMacro.toc? I don't really understand GitHub

**Comment by aurelion314** [comment] 2022-10-28 06:41
> @aurelion314 Do we need to download everything listed there, or just the SRC folder and MegaMacro.toc? I don't really understand GitHub

Yep src folder and MegaMacro.toc is enough.

**Comment by PunkROC01** [comment] 2022-10-28 06:49
> Yep src folder and MegaMacro.toc is enough.

Awesome! Thank you so much for the hard work fixing this. I use so many macros (especially mouseover for healing) and felt like I couldn't even play Pre-Patch because it was broken. Now I am very happily enjoying Pre-Patch!

**Comment by Sellorio** [comment] 2022-10-28 06:54
Release incoming.

You can use `/scripts/publish.bat` to copy the relevant files to the right folder.

**Comment by aurelion314** [comment] 2022-10-28 06:55
> Awesome! Thank you so much for the hard work fixing this. I use so many macros (especially mouseover for healing) and felt like I couldn't even play Pre-Patch because it was broken. Now I am very happily enjoying Pre-Patch!

Glad I could help! I was in the exact same situation and almost didn't want to play. 

@Sellorio Awesome! By the way, I added one more pull request that would be good to get into the release.

**Comment by Sellorio** [comment] 2022-10-28 07:04
Release created! I'll close this off and we can make a new issue if there's any outstanding issues.

@aurelion314 @Dannez83 hot off the heels of your Dragonflight updating, if you're interested in adding WoW Classic or fixing ElvUI support then I'm sure there's a bunch of potential and current users that'll appreciate it. If not then that's completely understandable too - after all, I could never be bothered with that haha.

**Closed by Sellorio** 2022-10-28 07:04 UTC

**Comment by aurelion314** [comment] 2022-10-28 07:15
@Sellorio Sounds good! I'm glad everything was fixable since it's a great addon. And thanks for sticking around to push the release. It's nice when the original upload is kept current.

I don't play classic or use ElvUI so can't help there. Maybe someone else in here can give it a go.
