### ISSUE TITLE
[mod:shift] Not working on some macros and posting errors

### ISSUE THREAD

**Issue by Magustar** [Sellorio/mega-macro#100] opened 2020-10-20 01:25 UTC
Macros show correctly in Macro UI but not in Action Bars noted in this screenshot;

![image](https://user-images.githubusercontent.com/73049124/96528642-e858a180-1248-11eb-969e-4db42899816e.png)

the contents of that macro are;

#showtooltip
/use [mod:shift] Wormhole Generator: Zandalar; Wormhole Generator: Kul Tiras

Macros have been imported from old UI.  I have tried recreating macros in new UI but with no luck in solving the issue.  The buttons do work but the "?" icon remains and the LUA errors pile up till a warning is given to shutdown Addons.

**Comment by Sellorio** [comment] 2020-10-20 01:27
Please provide the LUA error. You can gather this by installing the BugGrabber and BugSack addons. Also, which action bar addon are you using?

**Comment by Magustar** [comment] 2020-10-20 01:42
Not using any action bar addons just stock WoW UI.

**Comment by Magustar** [comment] 2020-10-20 01:49
![image](https://user-images.githubusercontent.com/73049124/96530200-87cb6380-124c-11eb-96cb-a5c3b4a3a83a.png)

**Comment by Sellorio** [comment] 2020-10-20 01:51
This is likely an issue specifically with the engineering item. Any chance you can cause this to happen with non-profession locked items/spells?

**Comment by Magustar** [comment] 2020-10-20 01:51
![image](https://user-images.githubusercontent.com/73049124/96530365-eabcfa80-124c-11eb-8753-816235d462d4.png)

**Comment by Magustar** [comment] 2020-10-20 01:53
You know you're right.  I do notice that it is all engineering items that are kicking up these errors.  I'll try with toys see if they have similar issues.

**Comment by Sellorio** [comment] 2020-10-20 01:56
If the engineering items count as toys with no spell that would seem to explain it. I've added some code in to handle that potential scenario. It'll be in 1.5.0 which is a day or 2 out probably. Alternatively, you can grab the latest Master and check with that. (I just committed the hopefully fix)

**Comment by Magustar** [comment] 2020-10-20 01:56
Getting errors with Toys as well;

![image](https://user-images.githubusercontent.com/73049124/96530680-8cdce280-124d-11eb-8213-c8e73f1964da.png)

Macro content

#showtooltip
/use {mod:shift] Hearthstone Board; Autographed Hearthstone Card

**Comment by Sellorio** [comment] 2020-10-20 01:59
You have a brace instead of open bracket btw.

**Comment by Sellorio** [comment] 2020-10-20 01:59
That could also cause this issue :D

**Comment by Sellorio** [comment] 2020-10-20 02:01
Just tested, looks like the brace shouldn't be the cause even if you did have it in your macro. Let me know if the current state of Master is also broken.

**Comment by Magustar** [comment] 2020-10-20 02:14
Try Chi Torpedo as a Mistweaver for some reason that one isn't working either.

**Comment by Magustar** [comment] 2020-10-20 02:15
Scratch that it came around after a Reload

**Comment by Sellorio** [comment] 2020-10-20 02:17
If you change talents then you currently need to reload to have that stuff fix itself.

**Comment by Magustar** [comment] 2020-10-20 02:19
Nothing un-bearable.  Changing zones causes all macro icon on toolbars to revert to "?" but a reload fixes it.

**Comment by Sellorio** [comment] 2020-10-20 02:20
I'll look right into that. I had previously solved that.

**Closed by Sellorio** 2020-10-20 02:20 UTC
Labels: bug

**Comment by Sellorio** [comment] 2020-10-20 02:22
Please join the discussion at #101.
